# Code Scanning Configuration

Navigate to: Settings → Code security and analysis → Code scanning → Protection rules

## Check runs failure threshold

### Recommended Setting: **High or higher**

Available options:
- **None** - No alerts block merging
- **Errors only** - Only errors block (not security alerts)  
- **High or higher** ← **SELECT THIS**
- **Medium or higher** - Too restrictive for most projects
- **Low or higher** - Very restrictive
- **All** - Includes informational notes (not recommended)

### What "High or higher" means:
- ❌ **Critical** severity: Blocks merge
- ❌ **High** severity: Blocks merge  
- ⚠️ **Medium** severity: Shows alert but doesn't block
- ℹ️ **Low** severity: Shows alert but doesn't block
- 📝 **Note/Info**: Shows but doesn't block

### Why this setting?
- Critical/High vulnerabilities are actual security risks
- Medium/Low findings are often false positives or minor issues
- Balances security with development speed

## Auto-dismiss Alerts

### Stale alerts
- Auto-dismiss alerts when the code they refer to is deleted
- Helps keep the alert list clean and actionable

### False positives
- Use "Dismiss alert" with reason when marking false positives
- Document why it's a false positive for future reference

## Alert Management

### Priority Order
1. **Critical**: Fix immediately, may require hotfix
2. **High**: Fix in current sprint/release
3. **Medium**: Fix in next release
4. **Low**: Fix when touching related code

### Review Process
- Security alerts should be reviewed weekly
- Assign owners to specific alert types
- Track remediation in project boards

## Integration with CI/CD

### Required Status Checks
Add these to branch protection:
- `CodeQL / Analyze (python)`
- `Docker Security Build / build-and-scan`

### Workflow Configuration
Workflows are configured to:
- Run on every push to main
- Run on all pull requests
- Run weekly scheduled scans
- Upload results to Security tab

## Tool-Specific Settings

### CodeQL
- Language: Python
- Query suite: Default (security-extended optional)
- Autofix: Enabled

### Container Scanning (Trivy)
- Severity filter: CRITICAL,HIGH
- Output: SARIF format
- Category: container-scan

### Dockerfile Linting (Hadolint)
- Format: SARIF
- Category: dockerfile-lint
- No-fail: true (warnings don't block)

## Notifications

### Alert Notifications
Configure in Settings → Notifications:
- Email: Security alerts for High/Critical
- GitHub: All security alerts
- Webhook: Optional for security tools

## Metrics and Reporting

Track these metrics:
- Mean Time to Remediate (MTTR) by severity
- Number of alerts by category
- False positive rate
- Security debt (open alerts)

## Exemptions

Some alerts may be exempted if:
1. Risk is accepted and documented
2. Compensating controls exist
3. Fix would break functionality

Document all exemptions in SECURITY.md