# Dependabot configuration for automated dependency updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    # Group updates to reduce PR noise
    groups:
      python-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "safety"  # Security tool - update separately
          - "bandit"  # Security tool - update separately
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Ignore major updates for critical packages
    ignore:
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Security tools - update more frequently
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    target-branch: "main"
    labels:
      - "security"
      - "dependencies"
    # Only security tools
    allow:
      - dependency-name: "safety"
      - dependency-name: "bandit"
      - dependency-name: "nuclei"
    commit-message:
      prefix: "security"
      include: "scope"
    open-pull-requests-limit: 5
    
