version: '3.8'

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: linknode-zap
    user: zap
    ports:
      - "8080:8080"
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.key=changeme
    networks:
      - security-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/JSON/core/view/version/?apikey=changeme"]
      interval: 30s
      timeout: 10s
      retries: 3

  linknode-tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linknode-security-tester
    depends_on:
      zap:
        condition: service_healthy
    environment:
      - LST_ZAP__HOST=zap
      - LST_ZAP__PORT=8080
      - LST_ZAP__API_KEY=changeme
    ports:
      - "8000:8000"
    volumes:
      - ./scan_results:/app/scan_results
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - security-network
    command: python main.py serve

networks:
  security-network:
    driver: bridge

volumes:
  scan_results: